### PR TITLE
Positioning and floating elements: NY Times article

### PR DESCRIPTION
**Pull request by felix-vondee**
In this project, we were required to:
 - Master CSS positioning
 - Get comfortable fixing linter errors
 - Get comfortable using git and github

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi Flex :wave: 

Your design looks good. To a large extent, you followed the semantic HTML guide. 

* However, in your HTML file, you should wrap the section with the: 

 ``` subscribe now and Login buttons; hamburger button, search icon, and website logo```
 with a **nav tag**.

 #### Here is the snapshot for reference. 

nav

* Enumerate what you have done in the project on your Pull request, by leaving a comment, in the comment textbox. Refer to this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

* Use Github [markdown](https://guides.github.com/features/mastering-markdown/) to format the contents in your readme.

#### That's it, make these changes, then submit another form for a code review.

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

**Comment by felix-vondee** [comment]
Changes Completed:
1) Wrapped section with the:
subscribe now and Login buttons; hamburger button, search icon, and the website logo
with a nav tag.
2) Used GitHub Markdown to format Readme.md file.

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @felix-vondee   ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**
- [x] You have to write a descriptive Pull Request Message with a descriptive title as well. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.

- [x] Also, your footer needs a little bit of work done on the subscribe column, see the image below for reference.

**Original** |  **Your clone**
------------ | -------------
Screenshot (71) | Screenshot (72)


**Optional**
- [ ] You can use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension tool to help select the right font-family used.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by felix-vondee** [comment]
Changes Completed:
- Fixed footer errors
- Fixed pull request naming and description

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @felix-vondee  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:
 

#### You may merge, good luck with your next projects! :rocket:

#### Happy Coding! :+1:

__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
